import {
  Hotel,
  Client,
  Booking,
  EmailTemplate,
  CompanySettings,
  Voucher,
  EmailLog,
  Lead,
  Tour,
  RoutePlan,
  Itinerary,
  TourCosting,
  Quotation,
  Invoice,
  Payment,
  SupplierPayment,
  OperationsItem,
  CalendarEvent,
  AuditLog,
  Supplier,
  TransportProvider,
  Activity,
  Restaurant,
  Guide,
  UniversalSupplierRate,
  TourTemplate,
  TourExpense,
  WhatsAppLog,
} from "./types";

export const initialCompanySettings: CompanySettings = {
  company_name: "Dodoz Leisure",
  logo_url: "",
  address: "No. 45, Galle Road, Colombo 03, Sri Lanka",
  phone: "+94 11 234 5678",
  whatsapp: "+94 77 123 4567",
  email: "reservations@dodozleisure.com",
  website: "www.dodozleisure.com",
  registration_number: "PV-108928",
  tax_number: "VAT-940028190",
  voucher_title: "HOTEL ACCOMMODATION VOUCHER",
  footer_note: "Thank you for partnering with Dodoz Leisure. Kindly confirm this booking with your hotel confirmation number.",
  terms: "All room allocations and meal plans are guaranteed as per the contract. Immediate notice required for room amendments.",
  smtp_provider: "Hostinger",
  smtp_host: "smtp.hostinger.com",
  smtp_port: 465,
  smtp_user: "reservations@dodozleisure.com",
  smtp_pass: "",
  smtp_secure: true,
  sender_name: "Dodoz Leisure Reservations",
  sender_email: "reservations@dodozleisure.com",
  base_currency: "USD",
  currencies: {
    USD: 1.0,
    LKR: 305.0,
    EUR: 0.92,
    GBP: 0.78,
    AUD: 1.52,
    INR: 83.5,
    AED: 3.67,
    CAD: 1.36,
  },
  tax_rate_percent: 18,
  service_charge_percent: 10,
  default_markup_percent: 20,
  route_provider: "matrix",
};

// ==========================================
// 1. Master Suppliers Directory
// ==========================================
export const initialSuppliers: Supplier[] = [
  {
    id: "sup-101",
    name: "The Kingsbury Hotel Colombo",
    type: "Hotel",
    contact_person: "Mr. Sanjeewa Perera",
    email: "reservations@thekingsburyhotel.com",
    phone: "+94 11 242 1051",
    whatsapp: "+94 77 345 6789",
    address: "48 Janadhipathi Mawatha, Colombo 01",
    city: "Colombo",
    country: "Sri Lanka",
    website: "www.thekingsburyhotel.com",
    currency: "USD",
    payment_terms: "30 Days Credit Account",
    active: true,
    rating: 5,
  },
  {
    id: "sup-102",
    name: "Heritance Kandalama (Aitken Spence)",
    type: "Hotel",
    contact_person: "Mr. Chaminda Bandara",
    email: "kandalama.res@heritancehotels.com",
    phone: "+94 66 555 5000",
    whatsapp: "+94 71 889 0123",
    address: "PO Box 11, Dambulla",
    city: "Dambulla",
    country: "Sri Lanka",
    website: "www.heritancehotels.com/kandalama",
    currency: "USD",
    payment_terms: "Direct Agency Account / 15 Days",
    active: true,
    rating: 5,
  },
  {
    id: "sup-103",
    name: "Lanka Luxury Wheels Fleet Co.",
    type: "Transport",
    contact_person: "Mr. Priyantha Jayasuriya",
    email: "dispatch@lankaluxurywheels.com",
    phone: "+94 11 445 6789",
    whatsapp: "+94 77 890 1234",
    address: "No. 88, Baseline Road, Colombo 09",
    city: "Colombo",
    country: "Sri Lanka",
    website: "www.lankaluxurywheels.com",
    currency: "USD",
    payment_terms: "Weekly Dispatch Statement",
    active: true,
    rating: 5,
  },
  {
    id: "sup-104",
    name: "Minneriya & Yala Wildlife Expeditions",
    type: "Activity",
    contact_person: "Mr. Samantha Weerasinghe",
    email: "bookings@yalasafarisrilanka.com",
    phone: "+94 47 223 9081",
    whatsapp: "+94 77 555 9012",
    address: "Palatupana Entrance Road, Yala",
    city: "Yala",
    country: "Sri Lanka",
    website: "www.yalasafarisrilanka.com",
    currency: "USD",
    payment_terms: "Net 7 Days",
    active: true,
    rating: 5,
  },
  {
    id: "sup-105",
    name: "The Grand Royal Restaurant Kandy",
    type: "Restaurant",
    contact_person: "Chef Nalaka Fernando",
    email: "dining@grandroyalkandy.com",
    phone: "+94 81 223 4455",
    whatsapp: "+94 76 112 3344",
    address: "24 Sangharaja Mawatha, Kandy",
    city: "Kandy",
    country: "Sri Lanka",
    currency: "USD",
    payment_terms: "Direct Settlement Voucher",
    active: true,
    rating: 4.8,
  },
  {
    id: "sup-106",
    name: "Sri Lanka Chauffeur Guides Guild",
    type: "Guide",
    contact_person: "Mr. Jagath Hettiarachchi",
    email: "info@chauffeursrilanka.org",
    phone: "+94 11 258 9012",
    whatsapp: "+94 77 990 0112",
    address: "Tourists Board Complex, Steuart Place, Colombo 03",
    city: "Colombo",
    country: "Sri Lanka",
    currency: "USD",
    payment_terms: "Daily Night-Out Allowance + End Tour Settlement",
    active: true,
    rating: 5,
  },
];

// ==========================================
// 2. Hotels & Dynamic Seasonal Contract Rates
// ==========================================
export const initialHotels: Hotel[] = [
  {
    id: "h-earls-regent",
    hotel_name: "EARLS REGENT",
    reservation_email: "reservations@earlsregent.com",
    cc_email: "fo@earlsregent.com",
    phone: "+94 81 222 3456",
    whatsapp: "+94 77 123 4567",
    address: "Devalakoppa, Kandy",
    city: "Kandy",
    country: "Sri Lanka",
    contact_person: "Mr. Samantha Bandara (Reservations Manager)",
    notes: "Preferred partner hotel in Kandy. Quick confirmation response.",
    active: true,
    star_rating: 4,
    currency: "USD",
  },
  {
    id: "h-araliya-red",
    hotel_name: "ARALIYA RED",
    reservation_email: "reservations@araliyared.com",
    cc_email: "res@araliyagroup.com",
    phone: "+94 52 222 9000",
    whatsapp: "+94 77 234 5678",
    address: "Upper Lake Road, Nuwara Eliya",
    city: "Nuwara Eliya",
    country: "Sri Lanka",
    contact_person: "Ms. Dilani Silva (Front Office Supervisor)",
    notes: "Modern luxury highland hotel in central Nuwara Eliya.",
    active: true,
    star_rating: 4,
    currency: "USD",
  },
  {
    id: "h-granbell",
    hotel_name: "GRANBELL",
    reservation_email: "reservations@granbellhotel.lk",
    cc_email: "info@granbellhotel.lk",
    phone: "+94 11 202 8888",
    whatsapp: "+94 77 345 6789",
    address: "282 Marine Drive, Kollupitiya, Colombo 03",
    city: "Colombo",
    country: "Sri Lanka",
    contact_person: "Mr. Kenji Tanaka / Front Desk",
    notes: "Japanese style oceanfront hotel with rooftop infinity pool.",
    active: true,
    star_rating: 4,
    currency: "USD",
  },
  {
    id: "h-earls-beruwela",
    hotel_name: "EARLS REGENT BERUWELA",
    reservation_email: "reservations.beruwela@earlshotels.com",
    cc_email: "fo.beruwela@earlshotels.com",
    phone: "+94 34 227 6000",
    whatsapp: "+94 77 456 7890",
    address: "Moragalla, Beruwela",
    city: "Beruwela",
    country: "Sri Lanka",
    contact_person: "Mr. Nalin Fernando",
    notes: "Beachfront resort with spa & banquet facilities.",
    active: true,
    star_rating: 4,
    currency: "USD",
  },
  {
    id: "h-cinnamon-grand",
    hotel_name: "CINNAMON GRAND",
    reservation_email: "grand@cinnamonhotels.com",
    cc_email: "res.grand@cinnamonhotels.com",
    phone: "+94 11 243 7437",
    whatsapp: "+94 77 567 8901",
    address: "77 Galle Road, Colombo 03",
    city: "Colombo",
    country: "Sri Lanka",
    contact_person: "Mr. Rohan Mendis",
    notes: "5-star flagship city hotel with 14 restaurants.",
    active: true,
    star_rating: 5,
    currency: "USD",
  },
  {
    id: "h-101",
    hotel_name: "The Kingsbury Colombo",
    reservation_email: "reservations@thekingsburyhotel.com",
    cc_email: "frontdesk@thekingsburyhotel.com",
    phone: "+94 11 242 1051",
    whatsapp: "+94 77 345 6789",
    address: "48 Janadhipathi Mawatha, Colombo 01",
    city: "Colombo",
    country: "Sri Lanka",
    contact_person: "Mr. Sanjeewa Perera",
    notes: "VIP guests, luxury ocean view preferred.",
    active: true,
    star_rating: 5,
    currency: "USD",
    rooms: [
      { id: "rm-101", hotel_id: "h-101", name: "Superior City View", room_type: "DBL", capacity_adults: 2, capacity_children: 1 },
      { id: "rm-102", hotel_id: "h-101", name: "Deluxe Ocean View", room_type: "DBL", capacity_adults: 2, capacity_children: 1 },
      { id: "rm-103", hotel_id: "h-101", name: "Executive Suite", room_type: "Suite", capacity_adults: 3, capacity_children: 2 },
    ],
    rates: [
      {
        id: "hr-101",
        hotel_id: "h-101",
        hotel_name: "The Kingsbury Colombo",
        room_type: "DBL",
        room_name: "Deluxe Ocean View",
        meal_plan: "BB",
        season_name: "Winter High Season 2026",
        valid_from: "2026-10-01",
        valid_until: "2027-04-30",
        single_rate: 130,
        double_rate: 150,
        twin_rate: 150,
        triple_rate: 195,
        extra_bed_rate: 45,
        child_with_bed_rate: 35,
        child_without_bed_rate: 15,
        currency: "USD",
      },
      {
        id: "hr-102",
        hotel_id: "h-101",
        hotel_name: "The Kingsbury Colombo",
        room_type: "DBL",
        room_name: "Deluxe Ocean View",
        meal_plan: "HB",
        season_name: "Winter High Season 2026",
        valid_from: "2026-10-01",
        valid_until: "2027-04-30",
        single_rate: 160,
        double_rate: 190,
        twin_rate: 190,
        triple_rate: 245,
        extra_bed_rate: 55,
        child_with_bed_rate: 45,
        child_without_bed_rate: 20,
        currency: "USD",
      },
    ],
  },
  {
    id: "h-102",
    hotel_name: "Heritance Kandalama",
    reservation_email: "kandalama.res@heritancehotels.com",
    cc_email: "frontoffice.kandalama@heritancehotels.com",
    phone: "+94 66 555 5000",
    whatsapp: "+94 71 889 0123",
    address: "PO Box 11, Dambulla",
    city: "Dambulla",
    country: "Sri Lanka",
    contact_person: "Mr. Chaminda Bandara",
    notes: "Geoffrey Bawa architectural masterpiece. Lake view rooms required.",
    active: true,
    star_rating: 5,
    currency: "USD",
    rooms: [
      { id: "rm-104", hotel_id: "h-102", name: "Superior Lake View", room_type: "DBL", capacity_adults: 2, capacity_children: 1 },
      { id: "rm-105", hotel_id: "h-102", name: "Luxury Panoramic Suite", room_type: "Suite", capacity_adults: 3, capacity_children: 2 },
    ],
    rates: [
      {
        id: "hr-103",
        hotel_id: "h-102",
        hotel_name: "Heritance Kandalama",
        room_type: "DBL",
        room_name: "Superior Lake View",
        meal_plan: "HB",
        season_name: "Winter High Season 2026",
        valid_from: "2026-10-01",
        valid_until: "2027-04-30",
        single_rate: 190,
        double_rate: 230,
        twin_rate: 230,
        triple_rate: 290,
        extra_bed_rate: 60,
        child_with_bed_rate: 50,
        child_without_bed_rate: 25,
        currency: "USD",
      },
    ],
  },
  {
    id: "h-103",
    hotel_name: "The Golden Crown Hotel Kandy",
    reservation_email: "reservations@goldencrownhotel.com",
    cc_email: "frontdesk@goldencrownhotel.com",
    phone: "+94 81 224 4000",
    whatsapp: "+94 77 445 5667",
    address: "322 Udagama, Ampitiya, Kandy",
    city: "Kandy",
    country: "Sri Lanka",
    contact_person: "Ms. Anoja Wijeratne",
    notes: "Mountain View luxury resort near Temple of Tooth.",
    active: true,
    star_rating: 5,
    currency: "USD",
    rates: [
      {
        id: "hr-104",
        hotel_id: "h-103",
        hotel_name: "The Golden Crown Hotel Kandy",
        room_type: "DBL",
        room_name: "Deluxe Mountain View",
        meal_plan: "HB",
        season_name: "Standard Contract 2026",
        valid_from: "2026-01-01",
        valid_until: "2026-12-31",
        single_rate: 140,
        double_rate: 170,
        twin_rate: 170,
        triple_rate: 220,
        extra_bed_rate: 50,
        child_with_bed_rate: 40,
        child_without_bed_rate: 18,
        currency: "USD",
      },
    ],
  },
  {
    id: "h-104",
    hotel_name: "Grand Hotel Nuwara Eliya",
    reservation_email: "reservations@thegrandhotel.lk",
    phone: "+94 52 222 2881",
    whatsapp: "+94 77 667 7889",
    address: "Grand Hotel Road, Nuwara Eliya",
    city: "Nuwara Eliya",
    country: "Sri Lanka",
    contact_person: "Mr. Ravi De Silva",
    notes: "Heritage Victorian property, high-tea coordination.",
    active: true,
    star_rating: 5,
    currency: "USD",
    rates: [
      {
        id: "hr-105",
        hotel_id: "h-104",
        hotel_name: "Grand Hotel Nuwara Eliya",
        room_type: "DBL",
        room_name: "Governor Deluxe Room",
        meal_plan: "HB",
        season_name: "Winter Season 2026",
        valid_from: "2026-10-01",
        valid_until: "2027-04-30",
        single_rate: 180,
        double_rate: 220,
        twin_rate: 220,
        triple_rate: 280,
        extra_bed_rate: 65,
        child_with_bed_rate: 55,
        child_without_bed_rate: 25,
        currency: "USD",
      },
    ],
  },
  {
    id: "h-105",
    hotel_name: "98 Acres Resort & Spa Ella",
    reservation_email: "reservations@resort98acres.com",
    phone: "+94 57 205 0050",
    whatsapp: "+94 77 112 2334",
    address: "Greenland Estate, Ella - Passara Road, Ella",
    city: "Ella",
    country: "Sri Lanka",
    contact_person: "Mr. Dinesh Rathnayake",
    notes: "Scenic luxury chalets overlooking Little Adam's Peak.",
    active: true,
    star_rating: 5,
    currency: "USD",
    rates: [
      {
        id: "hr-106",
        hotel_id: "h-105",
        hotel_name: "98 Acres Resort & Spa Ella",
        room_type: "DBL",
        room_name: "Premium Deluxe Chalet",
        meal_plan: "HB",
        season_name: "High Season 2026",
        valid_from: "2026-01-01",
        valid_until: "2026-12-31",
        single_rate: 240,
        double_rate: 280,
        twin_rate: 280,
        triple_rate: 350,
        extra_bed_rate: 80,
        child_with_bed_rate: 65,
        child_without_bed_rate: 30,
        currency: "USD",
      },
    ],
  },
  {
    id: "h-106",
    hotel_name: "Cinnamon Wild Yala",
    reservation_email: "wild@cinnamonhotels.com",
    phone: "+94 47 223 9404",
    whatsapp: "+94 77 778 8990",
    address: "Palatupana, Yala",
    city: "Yala",
    country: "Sri Lanka",
    contact_person: "Ms. Kanchana Senanayake",
    notes: "Safari lodge adjacent to Yala National Park.",
    active: true,
    star_rating: 5,
    currency: "USD",
    rates: [
      {
        id: "hr-107",
        hotel_id: "h-106",
        hotel_name: "Cinnamon Wild Yala",
        room_type: "DBL",
        room_name: "Jungle Chalet",
        meal_plan: "HB",
        season_name: "High Season 2026",
        valid_from: "2026-01-01",
        valid_until: "2026-12-31",
        single_rate: 190,
        double_rate: 230,
        twin_rate: 230,
        triple_rate: 290,
        extra_bed_rate: 60,
        child_with_bed_rate: 50,
        child_without_bed_rate: 25,
        currency: "USD",
      },
    ],
  },
  {
    id: "h-107",
    hotel_name: "Cape Weligama (Resplendent Ceylon)",
    reservation_email: "reservations@resplendentceylon.com",
    phone: "+94 11 774 5730",
    whatsapp: "+94 77 001 1223",
    address: "Abimanagama Road, Weligama",
    city: "Weligama",
    country: "Sri Lanka",
    contact_person: "Mr. Malik Fernando",
    notes: "Relais & Châteaux clifftop luxury villas.",
    active: true,
    star_rating: 5,
    currency: "USD",
    rates: [
      {
        id: "hr-108",
        hotel_id: "h-107",
        hotel_name: "Cape Weligama",
        room_type: "Villa",
        room_name: "Ocean Villa Suite",
        meal_plan: "HB",
        season_name: "Luxury Season 2026",
        valid_from: "2026-01-01",
        valid_until: "2026-12-31",
        single_rate: 450,
        double_rate: 520,
        twin_rate: 520,
        triple_rate: 650,
        extra_bed_rate: 120,
        child_with_bed_rate: 90,
        child_without_bed_rate: 40,
        currency: "USD",
      },
    ],
  },
  {
    id: "h-108",
    hotel_name: "Amangalla Galle Fort",
    reservation_email: "amangalla@aman.com",
    phone: "+94 91 223 3388",
    whatsapp: "+94 77 334 4556",
    address: "10 Church Street, Galle Fort",
    city: "Galle",
    country: "Sri Lanka",
    contact_person: "Mr. Lorenzo Menicacci",
    notes: "Ultra-luxury Aman historic residence inside UNESCO Fort.",
    active: true,
    star_rating: 5,
    currency: "USD",
    rates: [
      {
        id: "hr-109",
        hotel_id: "h-108",
        hotel_name: "Amangalla Galle Fort",
        room_type: "Suite",
        room_name: "Chamber Suite",
        meal_plan: "BB",
        season_name: "Aman Signature 2026",
        valid_from: "2026-01-01",
        valid_until: "2026-12-31",
        single_rate: 550,
        double_rate: 620,
        twin_rate: 620,
        triple_rate: 780,
        extra_bed_rate: 150,
        child_with_bed_rate: 110,
        child_without_bed_rate: 50,
        currency: "USD",
      },
    ],
  },
];

// ==========================================
// 3. Transport Providers & Fleets
// ==========================================
export const initialTransportProviders: TransportProvider[] = [
  {
    id: "tp-101",
    company_name: "Lanka Luxury Wheels Fleet Co.",
    contact_person: "Mr. Priyantha Jayasuriya",
    phone: "+94 11 445 6789",
    whatsapp: "+94 77 890 1234",
    email: "dispatch@lankaluxurywheels.com",
    address: "No. 88, Baseline Road, Colombo 09",
    currency: "USD",
    payment_terms: "Weekly Dispatch Invoice",
    active: true,
    vehicles: [
      {
        id: "v-101",
        transport_provider_id: "tp-101",
        vehicle_name: "Toyota Premio Executive Sedan",
        vehicle_class: "Car",
        registration_number: "WP CAB-4821",
        seats: 3,
        luggage_capacity: 2,
        air_conditioned: true,
        assigned_driver_name: "Gamini Wickremasinghe",
        assigned_driver_phone: "+94 77 234 5678",
        per_km_rate: 0.65,
        per_day_rate: 65,
        airport_transfer_rate: 45,
        extra_km_rate: 0.45,
      },
      {
        id: "v-102",
        transport_provider_id: "tp-101",
        vehicle_name: "Toyota HiAce Super Custom High-Roof Luxury Van",
        vehicle_class: "Van",
        registration_number: "WP ND-8910",
        seats: 7,
        luggage_capacity: 6,
        air_conditioned: true,
        assigned_driver_name: "Rohan Fernando",
        assigned_driver_phone: "+94 71 890 1234",
        per_km_rate: 0.85,
        per_day_rate: 85,
        airport_transfer_rate: 65,
        extra_km_rate: 0.55,
      },
      {
        id: "v-103",
        transport_provider_id: "tp-101",
        vehicle_name: "Toyota Land Cruiser Prado Luxury SUV",
        vehicle_class: "SUV",
        registration_number: "WP KX-9922",
        seats: 4,
        luggage_capacity: 4,
        air_conditioned: true,
        assigned_driver_name: "Upul Gunawardena",
        assigned_driver_phone: "+94 76 554 4332",
        per_km_rate: 1.25,
        per_day_rate: 130,
        airport_transfer_rate: 95,
        extra_km_rate: 0.75,
      },
      {
        id: "v-104",
        transport_provider_id: "tp-101",
        vehicle_name: "Toyota Coaster Luxury Mini Coach",
        vehicle_class: "Mini Bus",
        registration_number: "WP NA-4412",
        seats: 18,
        luggage_capacity: 15,
        air_conditioned: true,
        assigned_driver_name: "Mahinda Alwis",
        assigned_driver_phone: "+94 77 665 5443",
        per_km_rate: 1.6,
        per_day_rate: 165,
        airport_transfer_rate: 120,
        extra_km_rate: 0.95,
      },
    ],
    rates: {
      rate_type: "Per KM",
      base_rate: 85,
      per_km: 0.85,
      per_day: 85,
      extra_km_rate: 0.55,
      driver_daily_allowance: 20,
      night_surcharge: 15,
    },
  },
];

// ==========================================
// 4. Activity Providers & Excursions
// ==========================================
export const initialActivities: Activity[] = [
  {
    id: "act-101",
    name: "Sigiriya Lion Rock UNESCO Fortress Guided Climb",
    provider_name: "Central Cultural Triangle Heritage Board",
    location: "Sigiriya",
    duration: "3.5 Hours",
    adult_rate: 36,
    child_rate: 18,
    group_rate: 30,
    private_rate: 50,
    currency: "USD",
    guide_included: true,
    transport_included: false,
    entrance_included: true,
    opening_time: "06:30 AM",
    closing_time: "05:30 PM",
    description: "Iconic 5th century palace in the sky with ancient frescoes and mirror wall.",
    active: true,
  },
  {
    id: "act-102",
    name: "Minneriya National Park Wild Elephant Gathering 4x4 Jeep Safari",
    provider_name: "Eco Safari Sri Lanka",
    location: "Habarana / Minneriya",
    duration: "4 Hours",
    adult_rate: 65,
    child_rate: 35,
    group_rate: 55,
    currency: "USD",
    guide_included: true,
    transport_included: true,
    entrance_included: true,
    description: "Private open-top 4x4 safari tracker viewing herds of over 200 wild Asian elephants.",
    active: true,
  },
  {
    id: "act-103",
    name: "Temple of the Sacred Tooth Relic (Sri Dalada Maligawa) Tour",
    provider_name: "Kandy Heritage Custodians",
    location: "Kandy",
    duration: "2 Hours",
    adult_rate: 15,
    child_rate: 8,
    currency: "USD",
    guide_included: true,
    transport_included: false,
    entrance_included: true,
    description: "Sacred Buddhist shrine housing the tooth relic of Lord Buddha, with traditional drumming ceremony.",
    active: true,
  },
  {
    id: "act-104",
    name: "Pedro Estate Ceylon Tea Plantation & High-Tea Experience",
    provider_name: "Pedro Tea Estate Nuwara Eliya",
    location: "Nuwara Eliya",
    duration: "2.5 Hours",
    adult_rate: 22,
    child_rate: 12,
    currency: "USD",
    guide_included: true,
    transport_included: false,
    entrance_included: true,
    description: "Guided walk through misty tea gardens, factory manufacturing tour, and premium tea tasting session.",
    active: true,
  },
  {
    id: "act-105",
    name: "Yala National Park Premium Leopard Safari",
    provider_name: "Minneriya & Yala Wildlife Expeditions",
    location: "Yala",
    duration: "4.5 Hours",
    adult_rate: 85,
    child_rate: 45,
    currency: "USD",
    guide_included: true,
    transport_included: true,
    entrance_included: true,
    description: "Top-density leopard reserve tracking Sri Lankan leopards, sloth bears, and mugger crocodiles.",
    active: true,
  },
  {
    id: "act-106",
    name: "Mirissa Luxury Blue Whale & Dolphin Watching Ocean Cruise",
    provider_name: "Mirissa Water Sports & Ocean Safaris",
    location: "Mirissa Harbor",
    duration: "4 Hours",
    adult_rate: 60,
    child_rate: 30,
    currency: "USD",
    guide_included: true,
    transport_included: false,
    entrance_included: true,
    description: "Ocean catamaran cruise encountering Blue Whales, Sperm Whales, and spinner dolphin pods.",
    active: true,
  },
  {
    id: "act-107",
    name: "Galle Dutch Fort UNESCO Walking & Artisan Living History Tour",
    provider_name: "Southern Heritage Tours",
    location: "Galle Fort",
    duration: "2 Hours",
    adult_rate: 20,
    child_rate: 10,
    currency: "USD",
    guide_included: true,
    transport_included: false,
    entrance_included: true,
    description: "Walk the 17th-century ramparts, lighthouse, Dutch reformed church, and boutique artisan gemstone alleys.",
    active: true,
  },
];

// ==========================================
// 5. Restaurants
// ==========================================
export const initialRestaurants: Restaurant[] = [
  {
    id: "rst-101",
    name: "The Grand Royal Restaurant Kandy",
    location: "Kandy Lake Road",
    cuisine: "Traditional Sri Lankan & International Buffet",
    contact_person: "Chef Nalaka Fernando",
    phone: "+94 81 223 4455",
    whatsapp: "+94 76 112 3344",
    email: "dining@grandroyalkandy.com",
    currency: "USD",
    rates: {
      breakfast_rate: 12,
      lunch_rate: 18,
      dinner_rate: 22,
      buffet_rate: 18,
      set_menu_rate: 20,
      adult_rate: 18,
      child_rate: 9,
    },
    active: true,
  },
  {
    id: "rst-102",
    name: "Ministry of Crab Colombo",
    location: "Old Dutch Hospital, Colombo 01",
    cuisine: "World-Renowned Fresh Lagoon Crab & Seafood",
    contact_person: "Mr. Dharshan Munidasa",
    phone: "+94 11 234 2722",
    whatsapp: "+94 77 000 8899",
    email: "reservations@ministryofcrab.com",
    currency: "USD",
    rates: {
      lunch_rate: 65,
      dinner_rate: 85,
      set_menu_rate: 75,
      adult_rate: 75,
      child_rate: 35,
    },
    active: true,
  },
];

// ==========================================
// 6. Chauffeur & National Guides
// ==========================================
export const initialGuides: Guide[] = [
  {
    id: "gd-101",
    name: "Sunil Jayawardena",
    guide_type: "National Chauffeur Guide",
    languages: ["English", "German", "Sinhala"],
    location: "Colombo / Islandwide",
    phone: "+94 77 345 6789",
    whatsapp: "+94 77 345 6789",
    email: "sunil.tourguide@gmail.com",
    license_number: "SLTDA-CG-4829",
    daily_rate: 35,
    half_day_rate: 20,
    hourly_rate: 8,
    accommodation_required: true,
    daily_accommodation_rate: 25,
    currency: "USD",
    active: true,
  },
  {
    id: "gd-102",
    name: "Nimal Ranasinghe",
    guide_type: "National Chauffeur Guide",
    languages: ["English", "French", "Sinhala"],
    location: "Kandy / Central Highlands",
    phone: "+94 71 890 2345",
    whatsapp: "+94 71 890 2345",
    email: "nimal.guide.ceylon@gmail.com",
    license_number: "SLTDA-CG-5102",
    daily_rate: 40,
    half_day_rate: 25,
    accommodation_required: true,
    daily_accommodation_rate: 25,
    currency: "USD",
    active: true,
  },
];

// ==========================================
// 7. Universal Master Supplier Rates Table
// ==========================================
export const initialUniversalRates: UniversalSupplierRate[] = [
  {
    id: "usr-101",
    supplier_id: "h-101",
    supplier_name: "The Kingsbury Colombo",
    supplier_type: "Hotel",
    service_name: "Deluxe Ocean View (HB)",
    rate_type: "Per Room / Night",
    valid_from: "2026-10-01",
    valid_until: "2027-04-30",
    season: "Winter High",
    cost: 190,
    currency: "USD",
  },
  {
    id: "usr-102",
    supplier_id: "h-102",
    supplier_name: "Heritance Kandalama",
    supplier_type: "Hotel",
    service_name: "Superior Lake View (HB)",
    rate_type: "Per Room / Night",
    valid_from: "2026-10-01",
    valid_until: "2027-04-30",
    season: "Winter High",
    cost: 230,
    currency: "USD",
  },
  {
    id: "usr-103",
    supplier_id: "tp-101",
    supplier_name: "Lanka Luxury Wheels Fleet Co.",
    supplier_type: "Transport",
    service_name: "Toyota HiAce Super Custom Luxury Van",
    rate_type: "Per KM",
    valid_from: "2026-01-01",
    valid_until: "2026-12-31",
    cost: 0.85,
    currency: "USD",
  },
  {
    id: "usr-104",
    supplier_id: "act-101",
    supplier_name: "Central Cultural Triangle Heritage Board",
    supplier_type: "Activity",
    service_name: "Sigiriya Lion Rock Fortress Climb",
    rate_type: "Per Person",
    valid_from: "2026-01-01",
    valid_until: "2026-12-31",
    cost: 36,
    currency: "USD",
  },
  {
    id: "usr-105",
    supplier_id: "gd-101",
    supplier_name: "Sunil Jayawardena",
    supplier_type: "Guide",
    service_name: "National Chauffeur Guide (English)",
    rate_type: "Per Day",
    valid_from: "2026-01-01",
    valid_until: "2026-12-31",
    cost: 35,
    currency: "USD",
  },
];

// ==========================================
// 8. Clients & VIP Guests
// ==========================================
export const initialClients: Client[] = [
  {
    id: "c-101",
    name: "Dr. Jonathan Hayes & Family",
    email: "dr.jhayes@sydneyhealth.com.au",
    phone: "+61 412 345 678",
    whatsapp: "+61 412 345 678",
    nationality: "Australian",
    country: "Australia",
    passport_number: "PA9821039",
    passport_expiry: "2031-08-14",
    emergency_contact_name: "Mrs. Claire Hayes",
    emergency_contact_phone: "+61 412 345 679",
    is_corporate: false,
    dietary_requirements: "1 Guest Gluten-Free, 2 Standard",
    room_preferences: "Interconnecting deluxe rooms, high floor",
    travel_preferences: "Wildlife, heritage, private chauffeur, luxury boutique stays",
    tour_number: "DDL-2026-0001",
    reference: "SYD-HAYES-01",
    notes: "VIP guests celebrating 25th Wedding Anniversary. Complimentary cake & flowers arranged.",
    total_spent: 4080,
    tours_count: 1,
    created_at: "2026-08-10T10:00:00Z",
  },
  {
    id: "c-102",
    name: "Alexander & Sophia Lindqvist",
    email: "alex.lindqvist@nordictravel.se",
    phone: "+46 70 123 4567",
    whatsapp: "+46 70 123 4567",
    nationality: "Swedish",
    country: "Sweden",
    passport_number: "SE8829104",
    passport_expiry: "2029-12-01",
    is_corporate: false,
    dietary_requirements: "Vegetarian",
    room_preferences: "King Bed, Plunge pool villa preferred",
    travel_preferences: "Luxury Honeymoon, Tea trails, surfing, whale watching",
    tour_number: "DDL-2026-0002",
    reference: "SWE-HONEYMOON-26",
    notes: "Honeymoon amenities, private beachfront candlelit dinner included.",
    total_spent: 5850,
    tours_count: 1,
    created_at: "2026-08-15T11:30:00Z",
  },
  {
    id: "c-103",
    name: "Vantage Capital Partners (UK)",
    email: "events@vantagecap.co.uk",
    phone: "+44 20 7946 0912",
    whatsapp: "+44 77 0090 0123",
    nationality: "British",
    country: "United Kingdom",
    is_corporate: true,
    corporate_company_name: "Vantage Capital Partners Ltd",
    corporate_tax_number: "GB-992019482",
    corporate_billing_address: "100 Bishopsgate, London EC2N 4AG, UK",
    corporate_payment_terms: "30 Days Corporate Invoice",
    dietary_requirements: "Halal & Western options required",
    room_preferences: "Single executive rooms for all delegates",
    travel_preferences: "Executive corporate retreat, conference facilities, gala dinner",
    tour_number: "DDL-2026-0003",
    reference: "LON-CORP-09",
    total_spent: 14200,
    tours_count: 1,
    created_at: "2026-08-20T14:00:00Z",
  },
];

// ==========================================
// 9. CRM Leads & Inquiries
// ==========================================
export const initialLeads: Lead[] = [
  {
    id: "ld-101",
    lead_number: "INQ-2026-089",
    lead_date: "2026-09-01",
    source: "Website Direct Booking Form",
    client_name: "Dr. Jonathan Hayes & Family",
    country: "Australia",
    nationality: "Australian",
    email: "dr.jhayes@sydneyhealth.com.au",
    phone: "+61 412 345 678",
    whatsapp: "+61 412 345 678",
    adults_count: 2,
    children_count: 1,
    infants_count: 0,
    travel_start_date: "2026-10-15",
    travel_end_date: "2026-10-22",
    days_count: 8,
    nights_count: 7,
    destination: "Sri Lanka Island Classic (Sigiriya, Kandy, Nuwara Eliya, Yala, Galle)",
    budget: 4500,
    currency: "USD",
    travel_type: "Luxury Family Discovery",
    preferred_hotel_category: "5 Star Luxury",
    meal_plan: "HB",
    activities_requested: "Sigiriya Climb, Minneriya Safari, Kandy Temple, Tea Factory, Yala Leopard Safari",
    transport_requirement: "Private AC Luxury Van + Chauffeur Guide",
    guide_requirement: "English Speaking Tourist Guide",
    special_requirements: "Interconnecting rooms, anniversary cake",
    assigned_sales_person: "Shanika Perera",
    assigned_to: "Shanika Perera",
    folder: "Active Requests",
    status: "Confirmed",
    estimated_value: 4080,
    allocated_itinerary_id: "itin-101",
    allocated_itinerary_title: "8-Day Highlights of Ceylon Discovery",
    allocated_route_km: 865,
    converted_tour_id: "tour-101",
    created_at: "2026-08-10T09:30:00Z",
    activities: [
      { id: "la-1", lead_id: "ld-101", type: "Call", title: "Initial Consultation Call", details: "Client confirmed 8 days travel dates and 5-star hotel requirements.", performed_by: "Shanika Perera", created_at: "2026-08-10T11:00:00Z" },
      { id: "la-2", lead_id: "ld-101", type: "Quotation", title: "Dispatched 3-Tier Quotation", details: "Deluxe Option accepted at $4,080 USD.", performed_by: "Shanika Perera", created_at: "2026-08-11T14:30:00Z" },
    ],
  },
  {
    id: "ld-102",
    lead_number: "INQ-2026-092",
    lead_date: "2026-09-02",
    source: "Instagram Campaign / Honeymoon",
    client_name: "Alexander & Sophia Lindqvist",
    country: "Sweden",
    nationality: "Swedish",
    email: "alex.lindqvist@nordictravel.se",
    phone: "+46 70 123 4567",
    whatsapp: "+46 70 123 4567",
    adults_count: 2,
    children_count: 0,
    infants_count: 0,
    travel_start_date: "2026-11-05",
    travel_end_date: "2026-11-14",
    days_count: 10,
    nights_count: 9,
    destination: "Romantic Luxury & Coastal Villas (Tea Hills, Ella, Yala, Weligama)",
    budget: 6500,
    currency: "USD",
    travel_type: "Luxury Honeymoon",
    preferred_hotel_category: "Boutique Luxury Villas",
    meal_plan: "HB",
    status: "Confirmed",
    estimated_value: 5850,
    allocated_itinerary_id: "itin-102",
    allocated_itinerary_title: "10-Day Ceylon Romance & Ocean Odyssey",
    allocated_route_km: 740,
    converted_tour_id: "tour-102",
    created_at: "2026-08-15T10:00:00Z",
  },
  {
    id: "ld-103",
    lead_number: "INQ-2026-095",
    lead_date: "2026-09-04",
    source: "Corporate Referral",
    client_name: "Vantage Capital Partners (UK)",
    country: "United Kingdom",
    nationality: "British",
    email: "events@vantagecap.co.uk",
    phone: "+44 20 7946 0912",
    whatsapp: "+44 77 0090 0123",
    adults_count: 12,
    children_count: 0,
    travel_start_date: "2026-11-20",
    travel_end_date: "2026-11-26",
    days_count: 7,
    nights_count: 6,
    destination: "Colombo & Bentota Executive Retreat",
    budget: 16000,
    currency: "USD",
    travel_type: "Corporate Group",
    preferred_hotel_category: "5 Star Luxury",
    meal_plan: "FB",
    status: "Quotation Sent",
    estimated_value: 14200,
    allocated_route_km: 380,
    folder: "Corporate Groups",
    created_at: "2026-08-20T12:00:00Z",
  },
];

// ==========================================
// 10. Master Tours & Central Tour Workspaces
// ==========================================
export const initialTours: Tour[] = [
  {
    id: "tour-dl-001",
    tour_number: "DL-2026-001",
    tour_reference: "DL-2026-001",
    tour_name: "Sri Lanka 5-Day Highlights & Scenic Highlands",
    client_name: "Dr. Jonathan Hayes & Family",
    client_country: "Australia",
    client_email: "dr.jhayes@sydneyhealth.com.au",
    client_phone: "+61 412 345 678",
    destination: "Kandy → Nuwara Eliya → Colombo",
    start_date: "2026-06-10",
    end_date: "2026-06-15",
    arrival_date: "2026-06-10",
    departure_date: "2026-06-15",
    adults_count: 4,
    children_count: 0,
    infants_count: 0,
    total_pax: 4,
    pax: 4,
    nights_count: 4,
    days_count: 5,
    notes: "VIP group. Early check-in requested where available.",
    status: "Confirmed",
    currency: "USD",
    exchange_rate: 1.0,
    base_currency: "USD",
    total_cost: 3200,
    selling_price: 3850,
    gross_profit: 650,
    gross_margin_percent: 16.88,
    paid_amount: 3850,
    balance_due: 0,
    created_at: "2026-06-01T10:00:00Z",
    accommodation_rows: [
      {
        id: "acc-1",
        date: "10/06/2026",
        hotel: "EARLS REGENT",
        hotelName: "EARLS REGENT",
        hotelEmail: "reservations@earlsregent.com",
        sgl: 0,
        mealPlan: "HB",
        dbl: 70,
        tpl: 0,
        roomType: "Deluxe Room",
        specialRequest: "Early check-in requested",
      },
      {
        id: "acc-2",
        date: "11/06/2026",
        hotel: "EARLS REGENT",
        hotelName: "EARLS REGENT",
        hotelEmail: "reservations@earlsregent.com",
        sgl: 0,
        mealPlan: "HB",
        dbl: 70,
        tpl: 0,
        roomType: "Deluxe Room",
        specialRequest: "Close to elevator",
      },
      {
        id: "acc-3",
        date: "12/06/2026",
        hotel: "ARALIYA RED",
        hotelName: "ARALIYA RED",
        hotelEmail: "reservations@araliyared.com",
        sgl: 0,
        mealPlan: "HB",
        dbl: 100,
        tpl: 0,
        roomType: "Deluxe Mountain View",
        specialRequest: "High floor",
      },
      {
        id: "acc-4",
        date: "13/06/2026",
        hotel: "ARALIYA RED",
        hotelName: "ARALIYA RED",
        hotelEmail: "reservations@araliyared.com",
        sgl: 0,
        mealPlan: "HB",
        dbl: 100,
        tpl: 0,
        roomType: "Deluxe Mountain View",
        specialRequest: "Quiet room",
      },
      {
        id: "acc-5",
        date: "14/06/2026",
        hotel: "GRANBELL",
        hotelName: "GRANBELL",
        hotelEmail: "reservations@granbellhotel.lk",
        sgl: 0,
        mealPlan: "HB",
        dbl: 105,
        tpl: 0,
        roomType: "Superior Sea View",
        specialRequest: "Ocean view guaranteed",
      },
    ],
    transportation_rows: [
      { id: "tr-1", day: "DAY 1", route: "Kandy / Colombo", km: 190, vehicle_type: "Luxury AC Van" },
      { id: "tr-2", day: "DAY 2", route: "Nuwara Eliya scenic highlands", km: 300, vehicle_type: "Luxury AC Van" },
      { id: "tr-3", day: "DAY 3", route: "Tea Trails & Waterfalls excursion", km: 90, vehicle_type: "Luxury AC Van" },
      { id: "tr-4", day: "DAY 4", route: "Southern Expressway transfer", km: 80, vehicle_type: "Luxury AC Van" },
      { id: "tr-5", day: "DAY 5", route: "Colombo City & Airport Departure", km: 350, vehicle_type: "Luxury AC Van" },
    ],
    miscellaneous_rows: [
      { id: "m-1", item: "SANITIZER PACK", qty_value: 300 },
      { id: "m-2", item: "EXTRAS", qty_value: "" },
      { id: "m-3", item: "JEEP RATE", qty_value: 0 },
      { id: "m-4", item: "BOATS RATE", qty_value: 0 },
      { id: "m-5", item: "ENTRANCE FEES", qty_value: "" },
      { id: "m-6", item: "07 LUNCHES", qty_value: 70 },
      { id: "m-7", item: "KELANIYA TEMPLE", qty_value: 2 },
      { id: "m-8", item: "PINNAWELA", qty_value: 15 },
      { id: "m-9", item: "KANDY TEMPLE", qty_value: 6 },
    ],
  },
  {
    id: "tour-101",
    tour_number: "DDL-2026-0001",
    tour_name: "8-Day Highlights of Ceylon & Wildlife Discovery",
    client_id: "c-101",
    client_name: "Dr. Jonathan Hayes & Family",
    client_email: "dr.jhayes@sydneyhealth.com.au",
    client_phone: "+61 412 345 678",
    client_country: "Australia",
    destination: "Colombo → Sigiriya → Kandy → Nuwara Eliya → Yala → Galle",
    start_date: "2026-10-15",
    end_date: "2026-10-22",
    adults_count: 2,
    children_count: 1,
    infants_count: 0,
    total_pax: 3,
    nights_count: 7,
    days_count: 8,
    currency: "USD",
    exchange_rate: 1.0,
    base_currency: "USD",
    sales_agent: "Shanika Perera",
    operations_manager: "Nuwan Abeywickrama",
    status: "Confirmed",
    total_cost: 3400,
    selling_price: 4080,
    gross_profit: 680,
    gross_margin_percent: 16.67,
    paid_amount: 4080,
    balance_due: 0,
    created_at: "2026-08-11T12:00:00Z",
    days: [
      { day_number: 1, date: "2026-10-15", starting_location: "Airport", ending_location: "Negombo", intermediate_stops: ["Negombo Lagoon"], distance_km: 15, driving_time_mins: 25, hotel_name: "Jetwing Beach", meal_plan: "HB", activities: ["Airport VIP Welcome", "Sunset Beach Walk"], meals_included: ["Dinner"] },
      { day_number: 2, date: "2026-10-16", starting_location: "Negombo", ending_location: "Sigiriya", intermediate_stops: ["Dambulla Cave Temple"], distance_km: 155, driving_time_mins: 210, hotel_name: "Heritance Kandalama", meal_plan: "HB", activities: ["Dambulla Cave Temple Exploration", "Lake View High-Tea"], meals_included: ["Breakfast", "Dinner"] },
      { day_number: 3, date: "2026-10-17", starting_location: "Sigiriya", ending_location: "Sigiriya", intermediate_stops: ["Minneriya National Park"], distance_km: 45, driving_time_mins: 60, hotel_name: "Heritance Kandalama", meal_plan: "HB", activities: ["Sigiriya Lion Rock Fortress Climb", "Minneriya Wild Elephant Safari"], meals_included: ["Breakfast", "Dinner"] },
      { day_number: 4, date: "2026-10-18", starting_location: "Sigiriya", ending_location: "Kandy", intermediate_stops: ["Matale Spice Garden"], distance_km: 90, driving_time_mins: 150, hotel_name: "The Golden Crown Hotel Kandy", meal_plan: "HB", activities: ["Temple of the Tooth Relic", "Kandy Cultural Dance Show"], meals_included: ["Breakfast", "Dinner"] },
      { day_number: 5, date: "2026-10-19", starting_location: "Kandy", ending_location: "Nuwara Eliya", intermediate_stops: ["Ramboda Falls", "Tea Factory"], distance_km: 80, driving_time_mins: 160, hotel_name: "Grand Hotel Nuwara Eliya", meal_plan: "HB", activities: ["Pedro Tea Factory Tour", "Gregory Lake Stroll"], meals_included: ["Breakfast", "Dinner"] },
      { day_number: 6, date: "2026-10-20", starting_location: "Nuwara Eliya", ending_location: "Yala", intermediate_stops: ["Ella Gap", "Ravana Falls"], distance_km: 150, driving_time_mins: 210, hotel_name: "Cinnamon Wild Yala", meal_plan: "HB", activities: ["Nine Arch Bridge Walk", "Yala Afternoon Leopard Safari"], meals_included: ["Breakfast", "Dinner"] },
      { day_number: 7, date: "2026-10-21", starting_location: "Yala", ending_location: "Galle", intermediate_stops: ["Mirissa Coconut Tree Hill", "Stilt Fishermen"], distance_km: 135, driving_time_mins: 140, hotel_name: "The Fortress Resort & Spa", meal_plan: "HB", activities: ["Galle Dutch Fort UNESCO Walking Tour", "Sunset Cocktails on the Ramparts"], meals_included: ["Breakfast", "Dinner"] },
      { day_number: 8, date: "2026-10-22", starting_location: "Galle", ending_location: "Airport / Colombo", intermediate_stops: ["Colombo City Drive"], distance_km: 125, driving_time_mins: 110, meal_plan: "BB", activities: ["Souvenir Shopping", "Airport Departure Drop-off"], meals_included: ["Breakfast"] },
    ],
  },
  {
    id: "tour-102",
    tour_number: "DDL-2026-0002",
    tour_name: "10-Day Ceylon Romance, Highlands & Ocean Odyssey",
    client_id: "c-102",
    client_name: "Alexander & Sophia Lindqvist",
    client_email: "alex.lindqvist@nordictravel.se",
    client_phone: "+46 70 123 4567",
    client_country: "Sweden",
    destination: "Colombo → Kandy → Nuwara Eliya → Ella → Yala → Weligama",
    start_date: "2026-11-05",
    end_date: "2026-11-14",
    adults_count: 2,
    children_count: 0,
    infants_count: 0,
    total_pax: 2,
    nights_count: 9,
    days_count: 10,
    currency: "USD",
    exchange_rate: 1.0,
    base_currency: "USD",
    sales_agent: "Shanika Perera",
    operations_manager: "Nuwan Abeywickrama",
    status: "Confirmed",
    total_cost: 4850,
    selling_price: 5850,
    gross_profit: 1000,
    gross_margin_percent: 17.09,
    paid_amount: 3000,
    balance_due: 2850,
    created_at: "2026-08-16T10:00:00Z",
  },
];

// ==========================================
// 11. Dynamic Tour Costing Workspaces
// ==========================================
export const initialTourCostings: TourCosting[] = [
  {
    id: "cst-101",
    tour_id: "tour-101",
    tour_number: "DDL-2026-0001",
    tour_title: "8-Day Highlights of Ceylon & Wildlife Discovery",
    pax: 3,
    adults: 2,
    children: 1,
    currency: "USD",
    base_currency: "USD",
    exchange_rate: 1.0,
    items: [
      { id: "ci-1", costing_id: "cst-101", category: "Accommodation", service_name: "Jetwing Beach Negombo (1 DBL + 1 Extra Bed, HB)", supplier_id: "h-101", supplier_name: "Jetwing Hotels", day_number: 1, quantity: 1, unit: "Per Room", supplier_rate: 210, supplier_currency: "USD", exchange_rate_to_base: 1.0, converted_cost: 210, markup_type: "percentage", markup_value: 20, selling_price: 252, profit: 42, margin_percent: 16.67 },
      { id: "ci-2", costing_id: "cst-101", category: "Accommodation", service_name: "Heritance Kandalama (Superior Lake View, HB x 2 Nights)", supplier_id: "h-102", supplier_name: "Heritance Kandalama", day_number: 2, quantity: 2, unit: "Per Night", supplier_rate: 275, supplier_currency: "USD", exchange_rate_to_base: 1.0, converted_cost: 550, markup_type: "percentage", markup_value: 20, selling_price: 660, profit: 110, margin_percent: 16.67 },
      { id: "ci-3", costing_id: "cst-101", category: "Accommodation", service_name: "The Golden Crown Hotel Kandy (Deluxe Mountain View, HB)", supplier_id: "h-103", supplier_name: "The Golden Crown Hotel", day_number: 4, quantity: 1, unit: "Per Room", supplier_rate: 210, supplier_currency: "USD", exchange_rate_to_base: 1.0, converted_cost: 210, markup_type: "percentage", markup_value: 20, selling_price: 252, profit: 42, margin_percent: 16.67 },
      { id: "ci-4", costing_id: "cst-101", category: "Accommodation", service_name: "Grand Hotel Nuwara Eliya (Governor Deluxe, HB)", supplier_id: "h-104", supplier_name: "Grand Hotel Nuwara Eliya", day_number: 5, quantity: 1, unit: "Per Room", supplier_rate: 265, supplier_currency: "USD", exchange_rate_to_base: 1.0, converted_cost: 265, markup_type: "percentage", markup_value: 20, selling_price: 318, profit: 53, margin_percent: 16.67 },
      { id: "ci-5", costing_id: "cst-101", category: "Accommodation", service_name: "Cinnamon Wild Yala (Jungle Chalet, HB)", supplier_id: "h-106", supplier_name: "Cinnamon Wild Yala", day_number: 6, quantity: 1, unit: "Per Room", supplier_rate: 265, supplier_currency: "USD", exchange_rate_to_base: 1.0, converted_cost: 265, markup_type: "percentage", markup_value: 20, selling_price: 318, profit: 53, margin_percent: 16.67 },
      { id: "ci-6", costing_id: "cst-101", category: "Accommodation", service_name: "The Fortress Resort & Spa Galle (Ocean Room, HB)", supplier_id: "h-108", supplier_name: "The Fortress Resort", day_number: 7, quantity: 1, unit: "Per Room", supplier_rate: 300, supplier_currency: "USD", exchange_rate_to_base: 1.0, converted_cost: 300, markup_type: "percentage", markup_value: 20, selling_price: 360, profit: 60, margin_percent: 16.67 },
      { id: "ci-7", costing_id: "cst-101", category: "Transport", service_name: "Toyota HiAce Luxury Van (850 KM @ $0.85/KM + Tolls)", supplier_id: "tp-101", supplier_name: "Lanka Luxury Wheels Fleet Co.", quantity: 850, unit: "Per KM", supplier_rate: 0.85, supplier_currency: "USD", exchange_rate_to_base: 1.0, converted_cost: 722.5, markup_type: "percentage", markup_value: 20, selling_price: 867, profit: 144.5, margin_percent: 16.67 },
      { id: "ci-8", costing_id: "cst-101", category: "Transport", service_name: "Driver Night-Out Bata Allowance (7 Nights x $20)", supplier_id: "tp-101", supplier_name: "Lanka Luxury Wheels Fleet Co.", quantity: 7, unit: "Per Night", supplier_rate: 20, supplier_currency: "USD", exchange_rate_to_base: 1.0, converted_cost: 140, markup_type: "percentage", markup_value: 20, selling_price: 168, profit: 28, margin_percent: 16.67 },
      { id: "ci-9", costing_id: "cst-101", category: "Activity", service_name: "Sigiriya Lion Rock UNESCO Entrance (2 Adults + 1 Child)", supplier_id: "act-101", supplier_name: "Central Cultural Triangle", quantity: 3, unit: "Per Person", supplier_rate: 30, supplier_currency: "USD", exchange_rate_to_base: 1.0, converted_cost: 90, markup_type: "percentage", markup_value: 20, selling_price: 108, profit: 18, margin_percent: 16.67 },
      { id: "ci-10", costing_id: "cst-101", category: "Activity", service_name: "Minneriya National Park 4x4 Jeep Safari (3 Pax)", supplier_id: "act-102", supplier_name: "Eco Safari Sri Lanka", quantity: 1, unit: "Per Group", supplier_rate: 165, supplier_currency: "USD", exchange_rate_to_base: 1.0, converted_cost: 165, markup_type: "percentage", markup_value: 20, selling_price: 198, profit: 33, margin_percent: 16.67 },
      { id: "ci-11", costing_id: "cst-101", category: "Activity", service_name: "Yala National Park 4x4 Leopard Safari (3 Pax)", supplier_id: "act-105", supplier_name: "Yala Expeditions", quantity: 1, unit: "Per Group", supplier_rate: 195, supplier_currency: "USD", exchange_rate_to_base: 1.0, converted_cost: 195, markup_type: "percentage", markup_value: 20, selling_price: 234, profit: 39, margin_percent: 16.67 },
      { id: "ci-12", costing_id: "cst-101", category: "Guide", service_name: "National Chauffeur Guide (8 Days x $35)", supplier_id: "gd-101", supplier_name: "Sunil Jayawardena", quantity: 8, unit: "Per Day", supplier_rate: 35, supplier_currency: "USD", exchange_rate_to_base: 1.0, converted_cost: 280, markup_type: "percentage", markup_value: 20, selling_price: 336, profit: 56, margin_percent: 16.67 },
      { id: "ci-13", costing_id: "cst-101", category: "Guide", service_name: "Guide Separate Hotel Accommodation (7 Nights x $25)", supplier_id: "gd-101", supplier_name: "Sunil Jayawardena", quantity: 7, unit: "Per Night", supplier_rate: 25, supplier_currency: "USD", exchange_rate_to_base: 1.0, converted_cost: 175, markup_type: "percentage", markup_value: 20, selling_price: 210, profit: 35, margin_percent: 16.67 },
    ],
    total_accommodation_cost: 1800,
    total_transport_cost: 862.5,
    total_activities_cost: 450,
    total_guide_cost: 455,
    total_restaurants_cost: 0,
    total_other_cost: 0,
    total_net_cost: 3400,
    overall_markup_percent: 20,
    total_markup_amount: 680,
    gross_selling_price: 4080,
    net_selling_price: 4080,
    gross_profit: 680,
    gross_margin_percent: 16.67,
    cost_per_person: 1133.33,
    selling_per_person: 1360,
    status: "Approved",
    created_at: "2026-08-11T13:00:00Z",
  },
];

// ==========================================
// 12. Quotations
// ==========================================
export const initialQuotations: Quotation[] = [
  {
    id: "qt-101",
    quote_number: "QT-2026-0042",
    tour_id: "tour-101",
    lead_id: "ld-101",
    client_name: "Dr. Jonathan Hayes & Family",
    client_email: "dr.jhayes@sydneyhealth.com.au",
    client_phone: "+61 412 345 678",
    tour_name: "8-Day Highlights of Ceylon & Wildlife Discovery",
    travel_start_date: "2026-10-15",
    travel_end_date: "2026-10-22",
    duration_days: 8,
    total_pax: 3,
    currency: "USD",
    pricing_options: [
      { pricing_type: "Per Person", pax_label: "Adult (Double Sharing)", amount: 1360, currency: "USD" },
      { pricing_type: "Per Person", pax_label: "Child With Bed", amount: 680, currency: "USD" },
      { pricing_type: "Total Group", pax_label: "Total Family Package (3 Guests)", amount: 4080, currency: "USD" },
    ],
    total_amount: 4080,
    inclusions: [
      "7 Nights Accommodation in 5-Star & Premium Heritage Resorts",
      "Daily Buffet Breakfast and Dinner (Half Board Basis)",
      "Private Air-Conditioned Toyota Luxury High-Roof Van for entire tour",
      "Services of an English-Speaking National Tourist Chauffeur Guide",
      "Sigiriya Lion Rock UNESCO Entrance & Guided Tour",
      "Private 4x4 Open-Top Safari at Minneriya National Park",
      "Private 4x4 Leopard Safari at Yala National Park",
      "Temple of the Tooth Relic & Kandy Cultural Show tickets",
      "Pedro Tea Plantation Tour & Tasting",
      "Highway Tolls, Parking Fees, Fuel & Driver Night-Out Allowances",
      "Complimentary 25th Anniversary Cake & Welcome Drinks",
      "All Government Taxes, VAT & Service Charges",
    ],
    exclusions: [
      "International flights & Sri Lanka ETA Tourist Visa",
      "Lunch meals and alcoholic beverages",
      "Camera & video permit fees where applicable",
      "Personal expenses, laundry, and guide/driver gratuities",
    ],
    terms_and_conditions: "Quotation is valid for 14 days from issue date. Rooms are subject to availability upon confirmation.",
    payment_policy: "30% Advance deposit upon booking confirmation. 70% Balance due 14 days prior to arrival.",
    cancellation_policy: "Free cancellation up to 30 days prior to arrival. 50% refund between 15-29 days. Non-refundable within 14 days.",
    valid_until: "2026-09-30",
    status: "Accepted",
    created_at: "2026-08-11T14:00:00Z",
  },
];

// ==========================================
// 13. Invoices & Payments
// ==========================================
export const initialInvoices: Invoice[] = [
  {
    id: "inv-101",
    invoice_number: "INV-2026-0038",
    tour_id: "tour-101",
    tour_number: "DDL-2026-0001",
    client_id: "c-101",
    client_name: "Dr. Jonathan Hayes & Family",
    client_email: "dr.jhayes@sydneyhealth.com.au",
    client_address: "14 Ocean Street, Manly NSW 2095, Sydney, Australia",
    issue_date: "2026-08-12",
    due_date: "2026-09-15",
    items: [
      { id: "ii-1", description: "8-Day Highlights of Ceylon Tour Package (2 Adults)", quantity: 2, unit_price: 1360, amount: 2720 },
      { id: "ii-2", description: "Child with Bed Package (1 Child)", quantity: 1, unit_price: 1360, amount: 1360 },
    ],
    subtotal: 4080,
    tax_amount: 0,
    discount_amount: 0,
    total_amount: 4080,
    paid_amount: 4080,
    balance_due: 0,
    currency: "USD",
    status: "Paid",
    payment_instructions: "Payment received via International Wire Transfer. Bank Ref: ANZ-9948201.",
    created_at: "2026-08-12T10:00:00Z",
  },
  {
    id: "inv-102",
    invoice_number: "INV-2026-0041",
    tour_id: "tour-102",
    tour_number: "DDL-2026-0002",
    client_id: "c-102",
    client_name: "Alexander & Sophia Lindqvist",
    client_email: "alex.lindqvist@nordictravel.se",
    issue_date: "2026-08-16",
    due_date: "2026-10-01",
    items: [
      { id: "ii-3", description: "10-Day Ceylon Romance & Ocean Odyssey Package", quantity: 2, unit_price: 2925, amount: 5850 },
    ],
    subtotal: 5850,
    tax_amount: 0,
    discount_amount: 0,
    total_amount: 5850,
    paid_amount: 3000,
    balance_due: 2850,
    currency: "USD",
    status: "Partial",
    created_at: "2026-08-16T11:00:00Z",
  },
];

export const initialPayments: Payment[] = [
  {
    id: "pay-101",
    reference: "PAY-HAYES-DEP",
    invoice_id: "inv-101",
    tour_id: "tour-101",
    tour_number: "DDL-2026-0001",
    client_name: "Dr. Jonathan Hayes & Family",
    amount: 1500,
    currency: "USD",
    method: "Bank Transfer",
    date: "2026-08-12",
    status: "Received",
    transaction_receipt: "TT-ANZ-778810",
    notes: "30% Advance Deposit Received",
    created_at: "2026-08-12T15:00:00Z",
  },
  {
    id: "pay-102",
    reference: "PAY-HAYES-BAL",
    invoice_id: "inv-101",
    tour_id: "tour-101",
    tour_number: "DDL-2026-0001",
    client_name: "Dr. Jonathan Hayes & Family",
    amount: 2580,
    currency: "USD",
    method: "Bank Transfer",
    date: "2026-08-25",
    status: "Received",
    transaction_receipt: "TT-ANZ-990124",
    notes: "Full Balance Payment Cleared",
    created_at: "2026-08-25T11:00:00Z",
  },
];

export const initialSupplierPayments: SupplierPayment[] = [
  {
    id: "sp-101",
    tour_id: "tour-101",
    tour_number: "DDL-2026-0001",
    supplier_id: "h-102",
    supplier_name: "Heritance Kandalama",
    category: "Hotel",
    invoice_reference: "HK-INV-9901",
    amount: 550,
    currency: "USD",
    due_date: "2026-10-10",
    status: "Scheduled",
  },
  {
    id: "sp-102",
    tour_id: "tour-101",
    tour_number: "DDL-2026-0001",
    supplier_id: "tp-101",
    supplier_name: "Lanka Luxury Wheels Fleet Co.",
    category: "Transport",
    amount: 862.5,
    currency: "USD",
    due_date: "2026-10-14",
    status: "Pending",
  },
];

export const initialTourExpenses: TourExpense[] = [
  {
    id: "exp-101",
    tour_id: "tour-101",
    tour_number: "DDL-2026-0001",
    category: "Toll",
    description: "Southern Expressway & Central Expressway Tolls",
    amount: 35,
    currency: "USD",
    expense_date: "2026-10-15",
    recorded_by: "Nuwan Abeywickrama",
  },
  {
    id: "exp-102",
    tour_id: "tour-101",
    tour_number: "DDL-2026-0001",
    category: "Miscellaneous",
    description: "VIP Airport Welcome Garlands & Chilled Towels",
    amount: 25,
    currency: "USD",
    expense_date: "2026-10-15",
    recorded_by: "Shanika Perera",
  },
];

// ==========================================
// 14. Bookings & Multi-Category Vouchers
// ==========================================
export const initialBookings: Booking[] = [
  {
    id: "bk-101",
    booking_reference: "BK-2026-081",
    tour_id: "tour-101",
    tour_number: "DDL-2026-0001",
    client_name: "Dr. Jonathan Hayes & Family",
    supplier_name: "Heritance Kandalama",
    booking_type: "Hotel",
    hotel_name: "Heritance Kandalama",
    check_in_date: "2026-10-16",
    check_out_date: "2026-10-18",
    total_nights: 2,
    dbl_rooms: 1,
    room_type: "Superior Lake View (1 DBL + 1 Extra Bed)",
    meal_plan: "HB",
    confirmation_number: "HK-RES-9982",
    special_requests: "Geoffrey Bawa wing, adjoining rooms with view of Sigiriya Rock.",
    status: "Confirmed",
    total_cost: 550,
    currency: "USD",
    voucher_issued: true,
    voucher_id: "vch-101",
    created_at: "2026-08-12T14:00:00Z",
  },
  {
    id: "bk-102",
    booking_reference: "BK-2026-082",
    tour_id: "tour-101",
    tour_number: "DDL-2026-0001",
    client_name: "Dr. Jonathan Hayes & Family",
    supplier_name: "Lanka Luxury Wheels Fleet Co.",
    booking_type: "Transport",
    check_in_date: "2026-10-15",
    check_out_date: "2026-10-22",
    vehicle_details: "Toyota HiAce Super Custom Luxury High-Roof Van (WP ND-8910)",
    driver_assigned: "Gamini Wickremasinghe (+94 77 234 5678)",
    status: "Confirmed",
    total_cost: 862.5,
    currency: "USD",
    voucher_issued: true,
    voucher_id: "vch-102",
    created_at: "2026-08-12T14:30:00Z",
  },
  {
    id: "bk-103",
    booking_reference: "BK-2026-083",
    tour_id: "tour-101",
    tour_number: "DDL-2026-0001",
    client_name: "Dr. Jonathan Hayes & Family",
    supplier_name: "Eco Safari Sri Lanka",
    booking_type: "Activity",
    check_in_date: "2026-10-17",
    check_out_date: "2026-10-17",
    activity_details: "Minneriya National Park 4x4 Private Safari (3 Pax)",
    status: "Confirmed",
    total_cost: 165,
    currency: "USD",
    voucher_issued: true,
    created_at: "2026-08-12T15:00:00Z",
  },
];

export const initialVouchers: Voucher[] = [
  {
    id: "vch-101",
    voucher_number: "VCH-2026-081",
    voucher_type: "Hotel",
    booking_id: "bk-101",
    tour_id: "tour-101",
    tour_number: "DDL-2026-0001",
    client_name: "Dr. Jonathan Hayes & Family",
    supplier_name: "Heritance Kandalama",
    supplier_email: "kandalama.res@heritancehotels.com",
    supplier_phone: "+94 66 555 5000",
    reference: "SYD-HAYES-01",
    service_date: "2026-10-16",
    end_date: "2026-10-18",
    status: "sent",
    email_status: "sent",
    details: {
      rooms_schedule: [
        { date: "2026-10-16", hotel: "Heritance Kandalama", mealPlan: "HB", sgl: 0, dbl: 1, tpl: 0, roomType: "Superior Lake View", specialRequest: "Interconnecting rooms, lake view" },
        { date: "2026-10-17", hotel: "Heritance Kandalama", mealPlan: "HB", sgl: 0, dbl: 1, tpl: 0, roomType: "Superior Lake View", specialRequest: "Early breakfast for Sigiriya climb" },
      ],
      special_instructions: "Extend all VIP courtesies to Dr. Jonathan Hayes. All accommodation & stated meals to be billed to Dodoz Leisure direct account.",
    },
    sent_at: "2026-08-12T16:00:00Z",
    created_at: "2026-08-12T15:30:00Z",
  },
  {
    id: "vch-102",
    voucher_number: "VCH-2026-082",
    voucher_type: "Transport",
    booking_id: "bk-102",
    tour_id: "tour-101",
    tour_number: "DDL-2026-0001",
    client_name: "Dr. Jonathan Hayes & Family",
    supplier_name: "Lanka Luxury Wheels Fleet Co.",
    supplier_email: "dispatch@lankaluxurywheels.com",
    reference: "SYD-HAYES-01",
    service_date: "2026-10-15",
    end_date: "2026-10-22",
    status: "sent",
    email_status: "sent",
    details: {
      vehicle_type: "Toyota HiAce Super Custom High-Roof Luxury Van (WP ND-8910)",
      driver_name: "Gamini Wickremasinghe",
      driver_phone: "+94 77 234 5678",
      pickup_location: "Bandaranaike International Airport (CMB) Arrival Terminal",
      route_details: "Negombo → Sigiriya → Kandy → Nuwara Eliya → Yala → Galle → Colombo",
      pax_count: 3,
    },
    sent_at: "2026-08-12T16:15:00Z",
    created_at: "2026-08-12T15:45:00Z",
  },
];

// ==========================================
// 15. Operations Items & Master Calendar
// ==========================================
export const initialOperations: OperationsItem[] = [
  {
    id: "op-101",
    type: "arrival_placard",
    title: "VIP Airport Greeting Placard",
    tour_id: "tour-101",
    tour_number: "DDL-2026-0001",
    guest_name: "Dr. Jonathan Hayes & Family",
    pax_count: 3,
    flight_details: "Qatar Airways QR 668 at 08:30 AM",
    driver_name: "Gamini Wickremasinghe",
    driver_mobile: "+94 77 234 5678",
    driver_license: "B4829104",
    vehicle_type: "Toyota HiAce Super Custom Luxury Van",
    vehicle_plate: "WP ND-8910",
    date: "2026-10-15",
    status: "Ready",
    location: "CMB Airport Arrival Lobby",
  },
  {
    id: "op-102",
    type: "driver_manifest",
    title: "Official Chauffeur Driver Trip Manifest",
    tour_id: "tour-101",
    tour_number: "DDL-2026-0001",
    guest_name: "Dr. Jonathan Hayes & Family",
    pax_count: 3,
    flight_details: "QR 668 Arrival / EK 349 Departure",
    driver_name: "Gamini Wickremasinghe",
    driver_mobile: "+94 77 234 5678",
    vehicle_type: "Toyota HiAce Super Custom Luxury Van",
    vehicle_plate: "WP ND-8910",
    date: "2026-10-15",
    status: "Scheduled",
  },
];

export const initialCalendarEvents: CalendarEvent[] = [
  { id: "cal-1", title: "Tour Start: DDL-2026-0001 (Hayes Family)", date: "2026-10-15", type: "tour_start", tour_number: "DDL-2026-0001", client_name: "Dr. Jonathan Hayes & Family", hotel_or_location: "CMB Airport / Negombo", color: "emerald" },
  { id: "cal-2", title: "Check-in: Heritance Kandalama", date: "2026-10-16", type: "check_in", tour_number: "DDL-2026-0001", client_name: "Dr. Jonathan Hayes & Family", hotel_or_location: "Heritance Kandalama", color: "brand" },
  { id: "cal-3", title: "Excursion: Minneriya Safari", date: "2026-10-17", type: "excursion", tour_number: "DDL-2026-0001", client_name: "Dr. Jonathan Hayes & Family", hotel_or_location: "Minneriya National Park", color: "purple" },
  { id: "cal-4", title: "Supplier Due: Heritance Kandalama ($550)", date: "2026-10-10", type: "supplier_due", tour_number: "DDL-2026-0001", client_name: "Heritance Kandalama", hotel_or_location: "Accounts Payable", color: "amber" },
];

// ==========================================
// 16. Email & WhatsApp Templates
// ==========================================
export const initialEmailTemplates: EmailTemplate[] = [
  {
    id: "tpl-101",
    category: "hotel_voucher",
    name: "Hotel Accommodation Voucher Notification",
    subject: "Official Hotel Accommodation Voucher — {{TOUR_NUMBER}} ({{CLIENT_NAME}})",
    body: `Dear Reservations Team at {{HOTEL_NAME}},\n\nWarm greetings from Dodoz Leisure Sri Lanka!\n\nPlease find attached the official Hotel Accommodation Voucher for our valued guests, {{CLIENT_NAME}}, under Tour Reference {{TOUR_NUMBER}}.\n\nRESERVATION SUMMARY:\n• Guest / Party: {{CLIENT_NAME}} ({{PAX}} Pax)\n• Check-in Date: {{CHECK_IN}}\n• Check-out Date: {{CHECK_OUT}}\n• Total Rooms: {{TOTAL_ROOMS}}\n• Meal Basis: As indicated on attached PDF Voucher\n\nKindly confirm this reservation with your official Hotel Confirmation Number.\n\nWarm regards,\nDodoz Leisure Reservations Team\nHotline: +94 11 234 5678 | Web: www.dodozleisure.com`,
    is_default: true,
  },
  {
    id: "tpl-102",
    category: "supplier_request",
    name: "Hotel Room Availability & Rates Request",
    subject: "Availability & Rates Request — Tour {{TOUR_NUMBER}} ({{CHECK_IN}} to {{CHECK_OUT}})",
    body: `Dear Reservations Team at {{HOTEL_NAME}},\n\nCould you please check and confirm room availability and best contract rates for:\n\nTour Reference: {{TOUR_NUMBER}}\nGuest Name: {{CLIENT_NAME}}\nDates: {{CHECK_IN}} to {{CHECK_OUT}}\nRooms Required: {{TOTAL_ROOMS}}\nMeal Plan: {{MEAL_PLAN}}\nPax: {{PAX}} Guests\n\nPlease confirm availability at your earliest convenience.\n\nThank you,\nDodoz Leisure Reservations Desk`,
    is_default: false,
  },
  {
    id: "tpl-103",
    category: "client_quote",
    name: "Client Tour Itinerary & Quotation Proposal",
    subject: "Your Sri Lanka Tour Proposal & Quotation — {{TOUR_NAME}} (Dodoz Leisure)",
    body: `Dear {{CLIENT_NAME}},\n\nAyubowan & warm greetings from Dodoz Leisure Sri Lanka!\n\nWe are delighted to present your customized Sri Lanka travel proposal: {{TOUR_NAME}}.\n\nPlease find attached your comprehensive Day-by-Day Itinerary and Official Quotation.\n\nWe look forward to creating unforgettable Ceylon memories with you.\n\nWarm regards,\nDodoz Leisure Team`,
    is_default: false,
  },
];

export const initialEmailLogs: EmailLog[] = [
  {
    id: "log-1",
    recipient_email: "kandalama.res@heritancehotels.com",
    recipient_name: "Mr. Chaminda Bandara",
    hotel_name: "Heritance Kandalama",
    subject: "Official Hotel Accommodation Voucher — DDL-2026-0001 (Dr. Jonathan Hayes & Family)",
    status: "sent",
    voucher_number: "VCH-2026-081",
    tour_number: "DDL-2026-0001",
    sent_at: "2026-08-12T16:00:00Z",
  },
  {
    id: "log-2",
    recipient_email: "dispatch@lankaluxurywheels.com",
    recipient_name: "Mr. Priyantha Jayasuriya",
    subject: "Official Transport Voucher — DDL-2026-0001 (Toyota HiAce Super Custom)",
    status: "sent",
    voucher_number: "VCH-2026-082",
    tour_number: "DDL-2026-0001",
    sent_at: "2026-08-12T16:15:00Z",
  },
];

export const initialWhatsAppLogs: WhatsAppLog[] = [
  {
    id: "wa-1",
    phone: "+94718890123",
    recipient_name: "Heritance Kandalama Reservations",
    recipient_type: "Supplier",
    tour_number: "DDL-2026-0001",
    message_preview: "Dear Heritance Kandalama, please confirm availability for Tour DDL-2026-0001 from 2026-10-16 to 2026-10-18...",
    status: "Clicked",
    sent_at: "2026-08-12T16:20:00Z",
  },
];

// ==========================================
// 17. Reusable Tour Templates
// ==========================================
export const initialTourTemplates: TourTemplate[] = [
  {
    id: "tmpl-101",
    title: "8-Day Ceylon Classic Highlights (Cultural Triangle, Tea Hills & Yala)",
    code: "TMPL-8D-CLASSIC",
    duration_days: 8,
    duration_nights: 7,
    estimated_route_km: 850,
    summary: "The ultimate first-time traveler program covering UNESCO heritage, misty tea hills, wildlife safari, and Dutch maritime fort.",
    travel_style: "Classic Highlights",
    category: "Signature Tours",
    suggested_pax: 2,
    route_plan: {
      id: "rt-tmpl-1",
      title: "Colombo → Sigiriya → Kandy → Nuwara Eliya → Yala → Galle",
      day_count: 8,
      total_km: 850,
      total_driving_duration_mins: 1100,
      min_daily_km: 100,
      driver_daily_allowance: 20,
      waypoints: [],
      segments: [],
      provider: "matrix",
    },
    days: [],
  },
  {
    id: "tmpl-102",
    title: "10-Day Luxury Honeymoon & Coastal Romance",
    code: "TMPL-10D-HONEYMOON",
    duration_days: 10,
    duration_nights: 9,
    estimated_route_km: 740,
    summary: "Intimate boutique resorts, scenic highland trains, private wildlife safaris, and clifftop beach villas.",
    travel_style: "Luxury Honeymoon",
    category: "Romance & Honeymoon",
    suggested_pax: 2,
    route_plan: {
      id: "rt-tmpl-2",
      title: "Colombo → Kandy → Nuwara Eliya → Ella → Yala → Weligama",
      day_count: 10,
      total_km: 740,
      total_driving_duration_mins: 980,
      min_daily_km: 100,
      driver_daily_allowance: 20,
      waypoints: [],
      segments: [],
      provider: "matrix",
    },
    days: [],
  },
];

// ==========================================
// 18. Audit Logs
// ==========================================
export const initialAuditLogs: AuditLog[] = [
  {
    id: "aud-1",
    action: "Create",
    module: "Tours",
    user: "Shanika Perera",
    timestamp: "2026-08-11T12:00:00Z",
    record_id: "tour-101",
    details: "Created new Tour DDL-2026-0001 for client Dr. Jonathan Hayes & Family",
  },
  {
    id: "aud-2",
    action: "Approve",
    module: "Costing",
    user: "Nuwan Abeywickrama",
    timestamp: "2026-08-11T13:30:00Z",
    record_id: "cst-101",
    details: "Approved Costing with 16.67% Gross Margin ($680 Profit)",
  },
  {
    id: "aud-3",
    action: "Send",
    module: "Vouchers",
    user: "Shanika Perera",
    timestamp: "2026-08-12T16:00:00Z",
    record_id: "vch-101",
    details: "Dispatched Hotel Voucher VCH-2026-081 to Heritance Kandalama via Hostinger SMTP",
  },
];
