allprojects {
    buildscript {
        repositories {
            all { ArtifactRepository repo ->
                if (repo instanceof MavenArtifactRepository) {
                    if (repo.url.toString().contains("repo.maven.apache.org")) {
                        repo.url = uri("https://repo1.maven.org/maven2/")
                    }
                }
            }
        }
    }
    repositories {
        all { ArtifactRepository repo ->
            if (repo instanceof MavenArtifactRepository) {
                if (repo.url.toString().contains("repo.maven.apache.org")) {
                    repo.url = uri("https://repo1.maven.org/maven2/")
                }
            }
        }
    }
}
